services:
    app:
        build:
            context: .
            dockerfile: dockerfile
        ports:
            - "8000:80"
        volumes:
            - .:/var/www/html
        depends_on:
            - db
        environment:
            DB_HOST: db
            DB_DATABASE: laravel
            DB_USERNAME: laravel_user
            DB_PASSWORD: secret

    db:
        image: mysql:8.0
        platform: linux/arm64/v8  # Específico para Mac M1/M2
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: laravel
            MYSQL_USER: laravel_user
            MYSQL_PASSWORD: secret
            MYSQL_ROOT_PASSWORD: secret
        volumes:
            - mysql_data:/var/lib/mysql

    phpmyadmin:
        image: arm64v8/phpmyadmin  # Imagen compatible con Mac M1/M2
        ports:
            - "8080:80"
        environment:
            PMA_HOST: db
            MYSQL_ROOT_PASSWORD: secret
        depends_on:
            - db

volumes:
    mysql_data:
